# Generated by Django 5.0 on 2023-12-14 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatedirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiter_alert', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('contact_no_primary', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('contact_no_alternate', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('referred_by_other', models.CharField(blank=True, max_length=250, null=True)),
                ('address_line', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('notice_period', models.CharField(blank=True, max_length=50, null=True)),
                ('photo_path', models.TextField(blank=True, null=True)),
                ('resume_path', models.TextField(blank=True, null=True)),
                ('login_time', models.DateTimeField(blank=True, null=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=15, null=True)),
                ('geo_location', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('city', models.ForeignKey(blank=True, db_column='city', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crudapp.city')),
                ('education_level', models.ForeignKey(blank=True, db_column='education_level', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crudapp.educationlevel')),
                ('event', models.ForeignKey(blank=True, db_column='event', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crudapp.eventdetails')),
                ('experience_level', models.ForeignKey(blank=True, db_column='experience_level', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crudapp.experiencelevel')),
                ('gender', models.ForeignKey(blank=True, db_column='gender', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crudapp.gender')),
                ('job_position', models.ForeignKey(blank=True, db_column='job_position', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crudapp.jobrequisition')),
                ('marital_status', models.ForeignKey(blank=True, db_column='marital_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crudapp.maritalstatus')),
                ('persona', models.ForeignKey(blank=True, db_column='persona', default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crudapp.persona')),
                ('reason_for_change', models.ForeignKey(blank=True, db_column='reason_for_change', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crudapp.reasonforchange')),
                ('referred_by', models.ForeignKey(blank=True, db_column='referred_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crudapp.employeedirectory')),
                ('screening_mode', models.ForeignKey(blank=True, db_column='screening_mode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crudapp.screeningmode')),
            ],
        ),
    ]
