# Generated by Django 5.0 on 2023-12-14 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_candidatedirectory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatedirectory',
            options={'managed': False},
        ),
    ]
