# Generated by Django 5.0 on 2023-12-14 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_alter_candidatedirectory_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='candidatedirectory',
            table='crudapp_candidatedirectory',
        ),
    ]
